# -*- coding: utf-8 -*-
"""string18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string18
    import string
    text = input("Enter a string: ")
    starts = input("Enter starting word to check: ")
    ends = input("Enter ending word to check: ")
    if text.startswith(starts) and text.endswith(ends):
        print(f"String starts with '{starts}' and ends with '{ends}'")
    else:
        print("Doesn't match")

